spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartzdemo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

quartz:
  hello-message:
    job:
      name: job1
    trigger:
      name: trigger1
      group: group1